# Generated by Django 5.0.3 on 2024-03-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_remove_reservation_family_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='seat_number',
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
