# Generated by Django 5.0.3 on 2024-03-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_remove_reservation_seat_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
