# Generated by Django 5.0.3 on 2024-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_flight_max_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='available_seats',
            field=models.PositiveIntegerField(default=125),
        ),
    ]
